### ISSUE TITLE
What is the purpose of this provider?

### ISSUE THREAD

**Issue by petersg83** [shorwood/strapi-provider-upload-do#12]
Hello :)

I discovered this provider today and I was wondering why it was created.

Since Digital Ocean is AWS S3 compatible, the official provider `@strapi/provider-upload-aws-s3` can be used to connect to DO see: https://github.com/strapi/strapi/tree/main/packages/providers/upload-aws-s3#configuration-for-s3-compatible-services.

I was wondering if the official provider was enough or if it was missing something this provider is providing?

**Comment by petersg83** [comment]
Some answers from https://github.com/strapi/strapi/issues/15154#issuecomment-1357772744:

> The [built in support](https://github.com/shorwood/strapi-provider-upload-do/blob/363707c012d40ffe71f30a80a9288da8ba6b4675/lib/index.js#L6-L25) for "directories" (a filename prefix) and DigitalOceans CDN (a modification of the url stored on the file object.

**Comment by gcascio** [comment]
@petersg83  Do you think the mentioned functionality could make it into `@strapi/provider-upload-aws-s3 `? I guess the filename prefix could be added in a general fashion since it is useful in many scenarios. But I am unsure about the url modification.

**Comment by shorwood** [comment]
I agree, this codebase should be maintained by Strapi.

When I have the time, ill see if I can make a PR on the strapi repo to migrate this code to `@strapi/provider-upload-do`. It's been a long time I haven't worked with a Strapi project so it would be better for the maintenance of this package.
