### ISSUE TITLE
Prototype Pollution via file load in aws-sdk and @aws-sdk/shared-ini-file-loader

### ISSUE THREAD

**Issue by matteovivona** [shorwood/strapi-provider-upload-do#14]
Could you update this dependency? 
`aws-sdk@2.388.0` 

![Screenshot 2023-03-13 at 10 38 39](https://user-images.githubusercontent.com/6388707/224663614-e0b57246-9a07-4157-bf21-91f0acf2ad44.png)

**Comment by shorwood** [comment]
Done, sorry I forgot to update this issue.
